constructora/config/routes.rb
Rails.application.routes.draw do 

  resources :apartment_pictures
  get 'quotations/newfromrequest/', to: 'quotations#new'
  get 'quotations/newfromrequest/:id', to: 'quotations#newfromrequest'
  get 'apartment_bookings/newfromquotation/', to: 'apartment_bookings#new'
  get 'apartment_bookings/newfromquotation/:id', to: 'apartment_bookings#newfromquotation'
  get 'sales/newfromquotation/', to: 'sales#new'
  get 'sales/newfromquotation/:id', to: 'sales#newfromquotation'
  get 'sessions/new'
  resources :project_ap_type_prices
  resources :project_apartments
  resources :project_apartment_type_prices
  resources :project_apartment_types
  resources :sales
  resources :apartment_type_prices
  resources :banks
  resources :apartment_bookings
  resources :apartment_types
  resources :quotations
  resources :projects
  resources :request_quotations
  resources :appointments
  resources :users
 
  resources :clients
  resources :profiles
  resources :cities
  resources :states

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  #get 'administration/base_price'
  get 'administration/report'
  get 'administration/proforma'
  # get 'administration/register_sales'
  # get 'administration/separate_departament'
  # get 'administration/admin_quotes'
  get 'administration/intranet'

  # get 'login/signup'
  # get 'login/signin'
  get 'login/manager'
  # get 'login/password_recovery'

  # get 'sales/manager'
  # get 'sales/new'
  # get 'sales/edit'

  get 'quotation/manager'
  get 'quotation/new'
  get 'quotation/edit'

  # get 'requestquotation/manager'
  # get 'requestquotation/new'
  # get 'requestquotation/edit'

  get 'project/manager'
  get 'project/new'
  get 'project/edit'
  get 'project/details'

  get 'pages/aboutus'
  get 'pages/contactus'

  #root 'pages#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

constructora/app/models/appointment.rb
class Appointment < ApplicationRecord
	belongs_to :request_quotation
end

constructora/app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  layout "applicationintranet"
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    #@appointment.IdAppointment = SecureRandom.uuid
    
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
        if session[:s_request_quotation_id]
          format.html { redirect_to request_quotation_path(session[:s_request_quotation_id]), notice: 'Appointment was successfully destroyed.' }
        else 
          format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
        end
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:request_quotation_id, :AppointmentDate, :IsAttended)
    end
end

constructora/app/helpers/appointments_helper.rb
module AppointmentsHelper
end

constructora/app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h5 class="text-danger">Se encontraron los siguiente errores:</h5>

      <ul class="ml-3 text-danger">
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-3">
      <%= form.label :IdRequestQuotation, 'N° Solicitud' %>
    </div>
    <div class="col-sm-9">
      <%= 
      if session[:s_request_quotation_id]
        form.select :request_quotation_id, RequestQuotation.all.collect {|e| [e.id, e.id]}, { selected: session[:s_request_quotation_id] }, { class: "form-control" }
      else
        form.select :request_quotation_id, RequestQuotation.all.collect {|e| [e.id, e.id]}, {:include_blank => "Seleccione la Solicitud"}, {:class => "form-control"}
      end
      %>
    </div>
  </div>
  <div class="ml-3 mt-4 row">
    <div class="col-sm-3">
      <%= form.label :AppointmentDate, 'Fecha Cita' %>
    </div>
    <div class="col-sm-9">
      <%= form.datetime_select :AppointmentDate, :class => "form-control" %>
    </div>
  </div>
  <div class="ml-3 mt-4 row">
    <div class="col-sm-3">
      <%= form.label :IsAttended, 'Atendido' %>
    </div>
    <div class="col-sm-9">
      <%= form.check_box :IsAttended, :class => "checkBoxSyleForm" %>
    </div>
  </div>
  <br>

  <div class="actions">
    <%= form.submit "Guardar", :type => :image, :src => "/assets/SaveIconBig.png", :title => 'Guardar' %>
  </div>
<% end %>

constructora/app/views/appointments/edit.html.erb
<div class="jumbotron p-4">
  <h2><b>Editar | Citas</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', appointment: @appointment %>

	    <%= 
	      if session[:s_request_quotation_id]
	        link_to image_tag('BackIconBig.png'), request_quotation_path(session[:s_request_quotation_id]), title: 'Atras'
	      else 
	        link_to image_tag('BackIconBig.png'), appointments_path, title: 'Atras'
	      end
	    %>		
	</div>
</div>

constructora/app/views/appointments/index.html.erb
<div class="jumbotron p-4">
  <h2><b>Citas</b></h2>
  <p id="notice" class="badge badge-pill badge-danger pt-2 pb-2"><%= notice %></p>
  <div class="table-responsive-sm">
    <table class="table table-striped table-hover w-50">
      <thead class="thead-dark">
        <tr>
          <th colspan="3" class="text-center">
            <%= link_to image_tag('NewIcon.png'), new_appointment_path, title: 'Nuevo' %>
          </th>
          <th class="text-center">N° Solicitud</th>
          <th>Fecha Cita</th>
          <th class="text-center">Atendido</th>
        </tr>
      </thead>
      <%= session[:s_request_quotation_id] = nil %>
      <tbody>
        <% @appointments.each do |appointment| %>
          <tr>
            <td style="width:33px" class="pr-2 pl-2"><%= link_to image_tag('ShowIcon.png'), appointment, title: 'Ver' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('EditIcon.png'), edit_appointment_path(appointment), title: 'Editar' %></td>
            <td style="width:40px" class="pr-1 pl-2">
              <%= link_to image_tag('DeleteIcon.png'), appointment, title: 'Eliminar', method: :delete, data: { confirm: '¿Esta seguro?' } %>              
            </td>
            <td class="text-center"><%= RequestQuotation.select(:id).where("id = " + appointment.request_quotation_id.to_s).collect(&:id)[0] %></td>
            <td><%= appointment.AppointmentDate %></td>
            <td class="text-center">
              <%= check_box_tag "IsAttended", 0, appointment.IsAttended, disabled: true, class: "checkBoxSyleIndex" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

constructora/app/views/appointments/new.html.erb
<div class="jumbotron p-4">
  <h2><b>Nuevo | Citas</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', appointment: @appointment %>

	    <%= 
	      if session[:s_request_quotation_id]
	        link_to image_tag('BackIconBig.png'), request_quotation_path(session[:s_request_quotation_id]), title: 'Atras'
	      else 
	        link_to image_tag('BackIconBig.png'), appointments_path, title: 'Atras'
	      end
	    %>
	</div>
</div>

constructora/app/views/appointments/show.html.erb
<div class="jumbotron p-4">
  <h2><b>Ver | Citas</b></h2>
	<div class="table-responsive-sm w-50">
		<h5>
			<p id="notice" class="badge badge-pill badge-success pt-2 pb-2"><%= notice %></p>
		</h5>

		<p>
		  <strong>N° Solicitud:</strong>
		  <td><%= RequestQuotation.select(:id).where("id = " + @appointment.request_quotation_id.to_s).collect(&:id)[0] %></td>
		</p>

		<p>
		  <strong>Fecha Cita:</strong>
		  <%= @appointment.AppointmentDate %>
		</p>

		<p>
		  <strong>Atendido:</strong>
          <%= check_box_tag "IsActive", 0, @appointment.IsAttended, disabled: true, class: "checkBoxSyleIndex" %>
		</p>

		<%= link_to image_tag('EditIconBig.png'), edit_appointment_path(@appointment), title: 'Editar' %> |
	    <%= 
	      if session[:s_request_quotation_id]
	        link_to image_tag('BackIconBig.png'), request_quotation_path(session[:s_request_quotation_id]), title: 'Atras'
	      else 
	        link_to image_tag('BackIconBig.png'), appointments_path, title: 'Atras'
	      end
	    %>	

	</div>
</div>