constructora/config/routes.rb
Rails.application.routes.draw do 

  resources :apartment_pictures
  get 'quotations/newfromrequest/', to: 'quotations#new'
  get 'quotations/newfromrequest/:id', to: 'quotations#newfromrequest'
  get 'apartment_bookings/newfromquotation/', to: 'apartment_bookings#new'
  get 'apartment_bookings/newfromquotation/:id', to: 'apartment_bookings#newfromquotation'
  get 'sales/newfromquotation/', to: 'sales#new'
  get 'sales/newfromquotation/:id', to: 'sales#newfromquotation'
  get 'sessions/new'
  resources :project_ap_type_prices
  resources :project_apartments
  resources :project_apartment_type_prices
  resources :project_apartment_types
  resources :sales
  resources :apartment_type_prices
  resources :banks
  resources :apartment_bookings
  resources :apartment_types
  resources :quotations
  resources :projects
  resources :request_quotations
  resources :appointments
  resources :users
 
  resources :clients
  resources :profiles
  resources :cities
  resources :states

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  #get 'administration/base_price'
  get 'administration/report'
  get 'administration/proforma'
  # get 'administration/register_sales'
  # get 'administration/separate_departament'
  # get 'administration/admin_quotes'
  get 'administration/intranet'

  # get 'login/signup'
  # get 'login/signin'
  get 'login/manager'
  # get 'login/password_recovery'

  # get 'sales/manager'
  # get 'sales/new'
  # get 'sales/edit'

  get 'quotation/manager'
  get 'quotation/new'
  get 'quotation/edit'

  # get 'requestquotation/manager'
  # get 'requestquotation/new'
  # get 'requestquotation/edit'

  get 'project/manager'
  get 'project/new'
  get 'project/edit'
  get 'project/details'

  get 'pages/aboutus'
  get 'pages/contactus'

  #root 'pages#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

constructora/app/models/state.rb
class State < ApplicationRecord
	has_many :cities
	validates :Name, presence: {
		message: "es requerido."
	},
	length: 
	{
		maximum: 20,
		message: 'no debe ser mayor a 20 caracteres'
	}, 
	uniqueness: true
	{ 
		message: "ya existe"
	}
end

constructora/app/controllers/states_controller.rb
class StatesController < ApplicationController
  layout "applicationintranet"
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)
    #@state.IdState = SecureRandom.uuid

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'El departamento fue creado exitosamente.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'El departament fue actualizado exitosamente' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'El departamento fue eliminado existosamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:Name)
    end
end

constructora/app/helpers/states_helper.rb
module StatesHelper
end

constructora/app/views/states/_form.html.erb
<%= form_with(model: state, local: true) do |form| %>
  <% if state.errors.any? %>
    <div id="error_explanation">
      <h5 class="text-danger">Se encontraron los siguiente errores:</h5>

      <ul class="ml-3 text-danger">
      <% state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="field">
    <%= form.label :Name, 'Nombre' %>
    <%= form.text_field :Name, :class => "form-control" %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit "Guardar", :type => :image, :src => "/assets/SaveIconBig.png", :title => 'Guardar' %>
  </div>
<% end %>

constructora/app/views/states/edit.html.erb
<div class="jumbotron p-4">
  <h2><b>Editar | Ubigeo - Departamento</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', state: @state %>

		<%= link_to image_tag('ShowIconBig.png'), @state, title: 'Ver' %> |
		<%= link_to image_tag('BackIconBig.png'), states_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/states/index.html.erb
<div class="jumbotron p-4">
  <h2><b>Ubigeo - Departamentos</b></h2>
  <p id="notice" class="badge badge-pill badge-danger pt-2 pb-2"><%= notice %></p>
  <div class="table-responsive-sm">
    <table class="table table-striped table-hover w-50">
      <thead class="thead-dark">
        <tr>
          <th colspan="3" class="text-center">
            <%= link_to image_tag('NewIcon.png'), new_state_path, title: 'Nuevo' %>
          </th>
          <th>Nombre</th>
        </tr>
      </thead>

      <tbody>
        <% @states.each do |state| %>
          <tr>
            <td style="width:33px" class="pr-2 pl-2"><%= link_to image_tag('ShowIcon.png'), state, title: 'Ver' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('EditIcon.png'), edit_state_path(state), title: 'Editar' %></td>
            <td style="width:40px" class="pr-1 pl-2">
              <%= link_to image_tag('DeleteIcon.png'), state, title: 'Eliminar', method: :delete, data: { confirm: '¿Esta seguro?' } %>              
            </td>
            <td><%= state.Name %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

constructora/app/views/states/new.html.erb
<div class="jumbotron p-4">
  <h2><b>Nuevo | Ubigeo - Departamento</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', state: @state %>

		<%= link_to image_tag('BackIconBig.png'), states_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/states/show.html.erb
<div class="jumbotron p-4">
  <h2><b>Ver | Ubigeo - Departamento</b></h2>
	<div class="table-responsive-sm w-50">
		<h5>
			<p id="notice" class="badge badge-pill badge-success pt-2 pb-2"><%= notice %></p>
		</h5>		
		<hr>
		<p>
		  <strong>Name:</strong>
		  <%= @state.Name %>
		</p>
		<hr>
		<%= link_to image_tag('EditIconBig.png'), edit_state_path(@state), title: 'Editar' %> |
		<%= link_to image_tag('BackIconBig.png'), states_path, title: 'Atras'  %>
	</div>
</div>