constructora/config/routes.rb
Rails.application.routes.draw do 

  resources :apartment_pictures
  get 'quotations/newfromrequest/', to: 'quotations#new'
  get 'quotations/newfromrequest/:id', to: 'quotations#newfromrequest'
  get 'apartment_bookings/newfromquotation/', to: 'apartment_bookings#new'
  get 'apartment_bookings/newfromquotation/:id', to: 'apartment_bookings#newfromquotation'
  get 'sales/newfromquotation/', to: 'sales#new'
  get 'sales/newfromquotation/:id', to: 'sales#newfromquotation'
  get 'sessions/new'
  resources :project_ap_type_prices
  resources :project_apartments
  resources :project_apartment_type_prices
  resources :project_apartment_types
  resources :sales
  resources :apartment_type_prices
  resources :banks
  resources :apartment_bookings
  resources :apartment_types
  resources :quotations
  resources :projects
  resources :request_quotations
  resources :appointments
  resources :users
 
  resources :clients
  resources :profiles
  resources :cities
  resources :states

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  #get 'administration/base_price'
  get 'administration/report'
  get 'administration/proforma'
  # get 'administration/register_sales'
  # get 'administration/separate_departament'
  # get 'administration/admin_quotes'
  get 'administration/intranet'

  # get 'login/signup'
  # get 'login/signin'
  get 'login/manager'
  # get 'login/password_recovery'

  # get 'sales/manager'
  # get 'sales/new'
  # get 'sales/edit'

  get 'quotation/manager'
  get 'quotation/new'
  get 'quotation/edit'

  # get 'requestquotation/manager'
  # get 'requestquotation/new'
  # get 'requestquotation/edit'

  get 'project/manager'
  get 'project/new'
  get 'project/edit'
  get 'project/details'

  get 'pages/aboutus'
  get 'pages/contactus'

  #root 'pages#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

constructora/app/models/profile.rb
class Profile < ApplicationRecord
	has_many :users

	validates :Name, presence: {
		message: "es requerido."
	},
	length: 
	{
		maximum: 20,
		message: 'no debe ser mayor a 20 caracteres'
	}, 
	uniqueness: true
	{ 
		message: "ya existe"
	}
end

constructora/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "applicationintranet"
  before_action :set_profile, only: [:show, :edit, :update, :destroy]

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
    @profile.IsActive = true
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    #@profile.IdProfile = SecureRandom.uuid

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:Name, :IsActive)
    end
end

constructora/app/helpers/profiles_helper.rb
module ProfilesHelper
end

constructora/app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h5 class="text-danger">Se encontraron los siguiente errores:</h5>

      <ul class="ml-3 text-danger">
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="field">
    <%= form.label :Name, 'Nombre' %>
    <%= form.text_field :Name, :class => "form-control" %>
  </div>

  <div class="field mt-4">
    <%= form.label :IsActive, 'Activo' %>
    <%= form.check_box :IsActive, :class => "checkBoxSyleForm" %>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit "Guardar", :type => :image, :src => "/assets/SaveIconBig.png", :title => 'Guardar' %>
  </div>
<% end %>

constructora/app/views/profiles/edit.html.erb
<div class="jumbotron p-4">
  <h2><b>Editar | Perfiles</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', profile: @profile %>

		<%= link_to image_tag('ShowIconBig.png'), @profile, title: 'Ver' %> |
		<%= link_to image_tag('BackIconBig.png'), profiles_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/profiles/index.html.erb
<div class="jumbotron p-4">
  <h2><b>Perfiles</b></h2>
  <p id="notice" class="badge badge-pill badge-danger pt-2 pb-2"><%= notice %></p>
  <div class="table-responsive-sm">
    <table class="table table-striped table-hover w-50">
      <thead class="thead-dark">
        <tr>
          <th colspan="3" class="text-center">
            <%= link_to image_tag('NewIcon.png'), new_profile_path, title: 'Nuevo' %>
          </th>
          <th>Nombre</th>
          <th class="text-center">Activo</th>
        </tr>
      </thead>

      <tbody>
        <% @profiles.each do |profile| %>
          <tr>
            <td style="width:33px" class="pr-2 pl-2"><%= link_to image_tag('ShowIcon.png'), profile, title: 'Ver' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('EditIcon.png'), edit_profile_path(profile), title: 'Editar' %></td>
            <td style="width:40px" class="pr-1 pl-2">
              <%= link_to image_tag('DeleteIcon.png'), profile, title: 'Eliminar', method: :delete, data: { confirm: '¿Esta seguro?' } %>              
            </td>
            <td><%= profile.Name %></td>
            <td class="text-center">
              <%= check_box_tag "IsActive", 0, profile.IsActive, disabled: true, class: "checkBoxSyleIndex" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

constructora/app/views/profiles/new.html.erb
<div class="jumbotron p-4">
  <h2><b>Nuevo | Perfil</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', profile: @profile %>

		<%= link_to image_tag('BackIconBig.png'), profiles_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/profiles/show.html.erb
<div class="jumbotron p-4">
  <h2><b>Ver | Perfil</b></h2>
	<div class="table-responsive-sm w-50">
		<h5>
			<p id="notice" class="badge badge-pill badge-success pt-2 pb-2"><%= notice %></p>
		</h5>		
		<hr>
		<p>
		  <strong>Nombre:</strong>
		  <%= @profile.Name %>
		</p>
		<p>
		  <strong>Activo:</strong>		  
          <%= check_box_tag "IsActive", 0, @profile.IsActive, disabled: true, class: "checkBoxSyleIndex" %>
		</p>
		<hr>
		<%= link_to image_tag('EditIconBig.png'), edit_profile_path(@profile), title: 'Editar' %> |
		<%= link_to image_tag('BackIconBig.png'), profiles_path, title: 'Atras'  %>
	</div>
</div>