constructora/config/routes.rb
Rails.application.routes.draw do 

  resources :apartment_pictures
  get 'quotations/newfromrequest/', to: 'quotations#new'
  get 'quotations/newfromrequest/:id', to: 'quotations#newfromrequest'
  get 'apartment_bookings/newfromquotation/', to: 'apartment_bookings#new'
  get 'apartment_bookings/newfromquotation/:id', to: 'apartment_bookings#newfromquotation'
  get 'sales/newfromquotation/', to: 'sales#new'
  get 'sales/newfromquotation/:id', to: 'sales#newfromquotation'
  get 'sessions/new'
  resources :project_ap_type_prices
  resources :project_apartments
  resources :project_apartment_type_prices
  resources :project_apartment_types
  resources :sales
  resources :apartment_type_prices
  resources :banks
  resources :apartment_bookings
  resources :apartment_types
  resources :quotations
  resources :projects
  resources :request_quotations
  resources :appointments
  resources :users
 
  resources :clients
  resources :profiles
  resources :cities
  resources :states

  get 'signup'  => 'users#new'

  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  

  #get 'administration/base_price'
  get 'administration/report'
  get 'administration/proforma'
  # get 'administration/register_sales'
  # get 'administration/separate_departament'
  # get 'administration/admin_quotes'
  get 'administration/intranet'

  # get 'login/signup'
  # get 'login/signin'
  get 'login/manager'
  # get 'login/password_recovery'

  # get 'sales/manager'
  # get 'sales/new'
  # get 'sales/edit'

  get 'quotation/manager'
  get 'quotation/new'
  get 'quotation/edit'

  # get 'requestquotation/manager'
  # get 'requestquotation/new'
  # get 'requestquotation/edit'

  get 'project/manager'
  get 'project/new'
  get 'project/edit'
  get 'project/details'

  get 'pages/aboutus'
  get 'pages/contactus'

  #root 'pages#index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

constructora/app/models/quotation.rb
class Quotation < ApplicationRecord
	belongs_to :request_quotation
	belongs_to :client
	has_many :apartment_bookings
	has_many :sales

	validates :Price, presence: {
		message: "es requerido."
	}, 
	:numericality => 
	{ 
		:greater_than => 0, 
	  	message: ' debe ser mayor a 0'
	}

	validates :ValidFor, presence: {
		message: "es requerido."
	}, 
	:numericality => 
	{ 
		:greater_than => 0, 
	  	message: ' debe ser mayor a 0'
	}
	
	validates :Status, presence: {
		message: "es requerido."
	}
end

constructora/app/controllers/quotation_controller.rb
class QuotationController < ApplicationController
  def edit
  	render "pages/quotation/edit"
  end

  def manager
  	render "pages/quotation/manager"
  end

  def new
  	render "pages/quotation/new"
  end
end

constructora/app/controllers/quotations_controller.rb
class QuotationsController < ApplicationController
  layout "applicationintranet"
  before_action :set_quotation, only: [:show, :edit, :update, :destroy]

  # GET /quotations
  # GET /quotations.json
  def index
    @quotations = Quotation.all
  end

  # GET /quotations/1
  # GET /quotations/1.json
  def show
  end

  # GET /quotations/new
  def new
    @quotation = Quotation.new
    @quotation.Status = 0
  end

  # GET /quotations/newfromrequest/1
  def newfromrequest
    @quotation = Quotation.new
    @quotation.Status = 0
    
    begin
      #Setting up client
      request_quotation = RequestQuotation.find(params[:id])

      if request_quotation.Status != 0
        respond_to do |format|
          format.html { redirect_to request_quotations_url, notice: 'La solicitud ya tiene una cotización o esta rechazada.' }
          format.json { head :no_content }
        end
      else
        
        @quotation.request_quotation_id = request_quotation.id

        client = Client.find_by IdentityNumber: request_quotation.IdentityNumber
        if client == nil
          client = Client.new
          client.IdentityNumber = request_quotation.IdentityNumber
          client.Name = request_quotation.Name
          client.LastName = request_quotation.LastName
          client.Mail = request_quotation.Mail
          client.Phone = request_quotation.Phone
          client.IsActive = true
          client.save
        end
        
        @quotation.client_id = client.id

        #query_apartment_type = ProjectApartment.joins(project_apartment_type: :project_ap_type_price).select('project_apartments.id as pa_id, project_apartment_type.Area as pat_Area, project_apartment_type.Floor as pat_Floor, project_ap_type_prices.PercentajeDiscount as patp_PercentajeDiscount, project_ap_type_prices.Price as patp_Price').where('pa_id = ' + request_quotation.project_apartment_id.to_s)[0]
        
        #Computing Apartment Price
        ap_discount = 0
        query_apartment = ProjectApartment.joins(:project, :project_apartment_type).select('projects.price as p_Price, project_apartments.id as pa_id, project_apartment_types.id as pat_project_apartment_type_id, project_apartment_types.Area as pat_Area, project_apartment_types.Floor as pat_Floor').where('pa_id = ' + request_quotation.project_apartment_id.to_s)[0]
        query_apartment_discount = ProjectApTypePrice.where('IsActive = 1 and project_apartment_type_id = ' + query_apartment.pat_project_apartment_type_id.to_s)        
        query_apartment_discount.count
        
        ap_price = query_apartment.p_Price * query_apartment.pat_Area
        if query_apartment_discount.count > 0
          ap_discount = (ap_price / 100) * query_apartment_discount[0].PercentageDiscount
        end

        ap_floor_discount = (ap_price / 100) * (query_apartment.pat_Floor - 1)

        @quotation.Price = ap_price - ap_discount - ap_floor_discount

        render "quotations/new"
      end

    rescue ActiveRecord::RecordNotFound => e
      request_quotation = nil
    end    
  end

  # GET /quotations/1/edit
  def edit
  end

  # POST /quotations
  # POST /quotations.json
  def create
    @quotation = Quotation.new(quotation_params)

    if @quotation.request_quotation_id != nil
      request_quotation = RequestQuotation.find(@quotation.request_quotation_id)
      request_quotation.Status = 1
      request_quotation.save
    end

    #@quotation.IdQuotation = SecureRandom.uuid

    respond_to do |format|
      if @quotation.save
        format.html { redirect_to @quotation, notice: 'Quotation was successfully created.' }
        format.json { render :show, status: :created, location: @quotation }
      else
        format.html { render :new }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotations/1
  # PATCH/PUT /quotations/1.json
  def update
    respond_to do |format|
      if @quotation.update(quotation_params)
        format.html { redirect_to @quotation, notice: 'Quotation was successfully updated.' }
        format.json { render :show, status: :ok, location: @quotation }
      else
        format.html { render :edit }
        format.json { render json: @quotation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quotations/1
  # DELETE /quotations/1.json
  def destroy

    request_quotation = RequestQuotation.find(@quotation.request_quotation_id)
    request_quotation.Status = 0
    request_quotation.save

    @quotation.destroy

    respond_to do |format|
      format.html { redirect_to quotations_url, notice: 'Quotation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quotation
      @quotation = Quotation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quotation_params
      params.require(:quotation).permit(:request_quotation_id, :client_id, :QuotationDate, :Price, :ValidFor, :Status)
    end
end

constructora/app/helpers/quotations_helper.rb
module QuotationsHelper
end

constructora/app/views/quotations/_form.html.erb
<%= form_with(model: quotation, local: true) do |form| %>
  <% if quotation.errors.any? %>
    <div id="error_explanation">
      <h5 class="text-danger">Se encontraron los siguiente errores:</h5>

      <ul class="ml-3 text-danger">
      <% quotation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <hr>
  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :request_quotation_id, 'N° Solicitud' %>
    </div>
    <div class="col-sm-8">
      <%= form.select :request_quotation_id, RequestQuotation.all.collect {|e| [e.id, e.id]}, {:include_blank => "Seleccione la Solicitud"}, {:class => "form-control"} %>
    </div>
  </div>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :client_id, 'Cliente' %>
    </div>
    <div class="col-sm-8">
      <%= form.select :client_id, Client.all.order("Name asc").collect {|e| [e.Name + ' ' + e.LastName, e.id]}, {:include_blank => "Seleccione el Cliente"}, {:class => "form-control"} %>
    </div>
  </div>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :QuotationDate, 'Fecha Cotización' %>
    </div>
    <div class="col-sm-8">
      <%= form.date_select :QuotationDate, {:class => "form-control"} %>
    </div>
  </div>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :Price, 'Precio' %>
    </div>
    <div class="col-sm-8">
      <%= form.number_field :Price, {:class => "form-control"} %>
    </div>
  </div>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :ValidFor, 'Válido por' %>
    </div>
    <div class="col-sm-8">
      <%= form.number_field :ValidFor, {:class => "form-control"} %>
    </div>
  </div>

  <div class="ml-3 mt-4 row">
    <div class="col-sm-4">
      <%= form.label :Status, 'Estado' %>
    </div>
    <div class="col-sm-8">
    <%= form.select :Status, ([["Generado", "0"], ["Aprobado", "1"], ["Rechazado", "2"], ["Cancelado", "3"]]), {:class => "form-control"} %>      
    </div>
  </div>
  <hr>
  <div class="actions">
    <%= form.submit "Guardar", :type => :image, :src => "/assets/SaveIconBig.png", :title => 'Guardar' %>
  </div>
<% end %>

constructora/app/views/quotations/edit.html.erb
<div class="jumbotron p-4">
  <h2><b>Editar | Cotización</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', quotation: @quotation %>

		<%= link_to image_tag('ShowIconBig.png'), @quotation, title: 'Ver' %> |
		<%= link_to image_tag('BackIconBig.png'), quotations_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/quotations/index.html.erb
<div class="jumbotron p-4">
  <h2><b>Cotización</b></h2>
  <p id="notice" class="badge badge-pill badge-danger pt-2 pb-2"><%= notice %></p>
  <div class="table-responsive-sm">
    <table class="table table-striped table-hover w-100">
      <thead class="thead-dark">
        <tr>
          <th colspan="5" class="text-center">
            <%= link_to image_tag('NewIcon.png'), new_quotation_path, title: 'Nuevo' %>
          </th>
          <th class="text-center">Cotización</th>
          <th class="text-center">Solicitud</th>
          <th>Proyecto</th>
          <th class="text-center">Depart.</th>
          <th>Cliente</th>
          <th>Fecha</th>
          <th>Precio</th>
          <th>Válido por</th>
          <th>Estado</th>
        </tr>
      </thead>

      <tbody>
        <% @quotations.each do |quotation| %>
          <tr>
            <td style="width:33px" class="pr-2 pl-2"><%= link_to image_tag('ShowIcon.png'), quotation, title: 'Ver' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('EditIcon.png'), edit_quotation_path(quotation), title: 'Editar' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('NewDocIcon.png'), apartment_bookings_newfromquotation_path + '/' + quotation.id.to_s, title: 'Generar Reserva' %></td>
            <td style="width:33px" class="pr-1 pl-1"><%= link_to image_tag('NewSaleIcon.png'), sales_newfromquotation_path + '/' + quotation.id.to_s, title: 'Generar Reserva' %></td>            
            <td style="width:40px" class="pr-1 pl-2">
              <%= link_to image_tag('DeleteIcon.png'), quotation, title: 'Eliminar', method: :delete, data: { confirm: '¿Esta seguro?' } %></td>
            <td class="text-center"><%= quotation.id %></td>
            <td class="text-center"><%= RequestQuotation.select(:id).where("id = " + quotation.request_quotation_id.to_s).collect(&:id)[0] %></td>
            <td><%= RequestQuotation.joins(:project).select("request_quotations.id as rq_id, projects.Name as p_Name").where("rq_id = " + quotation.request_quotation_id.to_s).collect {|e| e.p_Name}[0]  %></td>
            <td class="text-center"><%= RequestQuotation.joins(:project_apartment).select("request_quotations.id as rq_id, project_apartments.Number as pa_Number").where("rq_id = " + quotation.request_quotation_id.to_s).collect {|e| e.pa_Number}[0] %></td>
            <td><%= Client.select(:Name, :LastName).where("id = " + quotation.client_id.to_s).collect {|e| e.Name + ' ' + e.LastName} [0] %></td>              
            </td>
            <td><%= quotation.QuotationDate %></td>
            <td><%= quotation.Price %></td>
            <td><%= quotation.ValidFor %></td>
            <td>
              <%=
              case quotation.Status
              when 0
                "Generado"
              when 1
                "Aprobado"
              when 2
                "Rechazado"
              when 3
                "Cancelado"
              else
                "No Definido"
              end %>              
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<br>

constructora/app/views/quotations/new.html.erb
<div class="jumbotron p-4">
  <h2><b>Nuevo | Cotización</b></h2>
	<div class="table-responsive-sm w-50">
		<%= render 'form', quotation: @quotation %>

		<%= link_to image_tag('BackIconBig.png'), quotations_path, title: 'Atras'  %>
	</div>
</div>

constructora/app/views/quotations/show.html.erb
<div class="jumbotron p-4">
  <h2><b>Ver | Cotizaciones</b></h2>
  <div class="table-responsive-sm w-50">
    <h5>
      <p id="notice" class="badge badge-pill badge-success pt-2 pb-2"><%= notice %></p>
    </h5>
    <hr>
    <p>
      <strong>N° de Cotización:</strong>
      <td><%= @quotation.id %></td>
    </p>

    <p>
      <strong>N° de Solicitud:</strong>
      <td><%= RequestQuotation.select(:id).where("id = " + @quotation.request_quotation_id.to_s).collect(&:id)[0] %></td>
    </p>

    <p>
      <strong>Proyecto:</strong>
      <td><%= RequestQuotation.joins(:project).select("request_quotations.id as rq_id, projects.Name as p_Name").where("rq_id = " + @quotation.request_quotation_id.to_s).collect {|e| e.p_Name}[0] %></td>
    </p>
    <p>
      <strong>Departamento:</strong>
      <td><%= RequestQuotation.joins(:project_apartment).select("request_quotations.id as rq_id, project_apartments.Number as pa_Number").where("rq_id = " + @quotation.request_quotation_id.to_s).collect {|e| e.pa_Number}[0] %></td>
    </p>        

    <p>
      <strong>Cliente:</strong>
      <td><%= Client.select(:Name).where("id = " + @quotation.client_id.to_s).collect(&:Name)[0] %></td>
    </p>

    <p>
      <strong>Fecha:</strong>
      <%= @quotation.QuotationDate %>
    </p>

    <p>
      <strong>Precio:</strong>
      <%= @quotation.Price %>
    </p>

    <p>
      <strong>Válido por:</strong>
      <%= @quotation.ValidFor %>
    </p>

    <p>
      <strong>Estado:</strong>
      <%=
      case @quotation.Status
      when 0
        "Generado"
      when 1
        "Aprobado"
      when 2
        "Rechazado"
      when 3
        "Cancelado"        
      else
        "No Definido"
      end %>
    </p>
    <hr>
    <%= link_to image_tag('EditIconBig.png'), edit_quotation_path(@quotation), title: 'Editar' %> |
    <%= link_to image_tag('BackIconBig.png'), quotations_path, title: 'Atras'  %>

  </div>
</div>